/**
 * AICopilot.js
 * LLM AI Copilot Interface Module for Circuit Diagnostics & Signal Analysis.
 */

export class AICopilot {
    constructor(apiEndpoint = null, apiKey = null) {
        this.apiEndpoint = apiEndpoint;
        this.apiKey = apiKey;
    }

    /**
     * Solicits analysis from AI Copilot (Mock or REST API call).
     * @param {Object} telemetry - Circuit telemetry JSON generated by SPICEExporter
     * @param {string} userQuery - Optional custom user prompt
     * @returns {Promise<string>} - AI Response Markdown text
     */
    async analyzeCircuit(telemetry, userQuery = null) {
        // If live API endpoint configured, send POST request
        if (this.apiEndpoint && this.apiKey) {
            try {
                const response = await fetch(this.apiEndpoint, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${this.apiKey}`
                    },
                    body: JSON.stringify({
                        telemetry,
                        prompt: userQuery || "Analyze this electronic circuit graph, transient waveform, and frequency spectrum for issues and performance metrics."
                    })
                });

                if (response.ok) {
                    const data = await response.json();
                    return data.analysis || data.choices?.[0]?.message?.content || JSON.stringify(data);
                }
            } catch (err) {
                console.warn('Live AI API call failed, falling back to Intelligent Local Copilot:', err);
            }
        }

        // Fallback: High-quality rule-based Intelligent Mock LLM Copilot Engine
        return this.generateMockAnalysis(telemetry, userQuery);
    }

    generateMockAnalysis(telemetry, userQuery) {
        const comps = telemetry.components || {};
        const compList = Object.values(comps);

        let resistor = compList.find(c => c.type === 'R');
        let capacitor = compList.find(c => c.type === 'C');
        let dcSrc = compList.find(c => c.type === 'VDC');
        let sw = compList.find(c => c.type === 'SWITCH');

        let rVal = resistor ? resistor.value : 1000;
        let cVal = capacitor ? capacitor.value : 10e-6;
        let tau = rVal * cVal; // RC time constant
        let fc = 1 / (2 * Math.PI * tau); // Cutoff frequency

        const stats = telemetry.oscilloscope || {};
        const peakFreq = telemetry.spectrum?.peakFreqHz || 0;

        let markdown = `### 🤖 AI Circuit Copilot Analysis Report\n\n`;

        if (userQuery && userQuery.includes('fc')) {
            markdown += `**차단 주파수 (Cut-off Frequency $f_c$) 계산:**\n`;
            markdown += `- 저항값 ($R$): **${rVal >= 1000 ? (rVal / 1000) + ' kΩ' : rVal + ' Ω'}**\n`;
            markdown += `- 커패시턴스 ($C$): **${(cVal * 1e6).toFixed(1)} µF**\n`;
            markdown += `- 시상수 ($\tau = R \\times C$): **${(tau * 1000).toFixed(2)} ms**\n`;
            markdown += `- 이론적 차단 주파수 ($f_c = \\frac{1}{2\\pi RC}$): **${fc.toFixed(2)} Hz**\n\n`;
            return markdown;
        }

        markdown += `#### 1. 회로 구성망 (Circuit Topology)\n`;
        markdown += `- **DC 전원**: ${dcSrc ? dcSrc.value + 'V' : '미연결'}\n`;
        markdown += `- **RC 직렬 필터**: $R = ${rVal >= 1000 ? (rVal / 1000) + ' kΩ' : rVal + ' Ω'}$, $C = ${(cVal * 1e6).toFixed(1)} \\mu\\text{F}$\n`;
        markdown += `- **스위치 상태**: ${sw ? (sw.value > 100 ? '🔴 OPEN (차단)' : '🟢 CLOSED (도통)') : 'N/A'}\n\n`;

        markdown += `#### 2. 과도 응답 및 과도 특성 (Transient Response)\n`;
        markdown += `- **이론적 시상수 ($\tau$)**: **${(tau * 1000).toFixed(2)} ms**\n`;
        markdown += `- **최대 전압 ($V_{\\max}$)**: ${stats.vmax ? stats.vmax.toFixed(2) + 'V' : '0.00V'}\n`;
        markdown += `- **Peak-to-Peak ($V_{pp}$)**: ${stats.vpp ? stats.vpp.toFixed(2) + 'V' : '0.00V'}\n\n`;

        markdown += `#### 3. 주파수 영역 FFT 분석 (Frequency Response)\n`;
        markdown += `- **이론적 1차 RC 차단 주파수 ($f_c$)**: **${fc.toFixed(2)} Hz**\n`;
        markdown += `- **실측 Peak 주파수**: **${peakFreq.toFixed(1)} Hz**\n\n`;

        markdown += `#### 💡 진단 및 추천 (AI Recommendation)\n`;
        if (sw && sw.value > 100) {
            markdown += `⚠️ **경고**: 현재 스위치가 열려(OPEN) 있어 전류가 흐르지 않습니다. '스위치 토글' 버튼을 클릭하거나 스위치를 닫아 충전 파형을 관찰하세요.\n`;
        } else {
            markdown += `✅ **정상 작동**: 커패시터 충전 파형이 지수함수 $v_C(t) = V_{DC}(1 - e^{-t/\\tau})$ 궤적을 따라 정상 형성되고 있습니다.\n`;
            markdown += `- **Tip**: 저항이나 커패시터 값을 변경하면 계측기 화면에서 시상수 $\\tau$ 와 FFT 주파수 스펙트럼 차단점이 즉시 갱신됩니다.\n`;
        }

        return markdown;
    }
}
